### ISSUE TITLE
use shellcheck to lint shell scripts

### ISSUE THREAD

**Issue by yoshuawuyts** [man-n/man-n#12]
[`shellcheck(1)`](http://www.shellcheck.net/) lints shell scripts very neatly. There's currently no way of getting shellcheck to download and work cross-platform through npm. Before adding the checker to an `npm test` script a module must be built; any suggestions to add it in another way are welcome!

**Comment by yoshuawuyts** [comment]
We can probably steal some code from - https://github.com/wercker/step-shellcheck/blob/master/wercker.yml

**Comment by wooorm** [comment]
Yeah that’s fine with me. Want to go for it?

**Comment by yoshuawuyts** [comment]
You're welcome to do it if you want to; it's probably something that's needed for multiple projects anyway. I don't think I'll have enough time to make it happen in the next 1-2 weeks.

**Comment by wooorm** [comment]
I’d love to, but will also keep it on the back burner!
