### ISSUE TITLE
strip badges?

### ISSUE THREAD

**Issue by yoshuawuyts** [man-n/man-n#2]
Badge blocks look sort of weird in man pages, mayhaps we should strip 'em?

<img width="639" alt="screen shot 2015-07-05 at 10 44 44" src="https://cloud.githubusercontent.com/assets/2467194/8510981/e4323c14-2302-11e5-969f-b1aabe4ad43b.png">

**Comment by wooorm** [comment]
Agreed. Know of a list of badge URLs? I mean, there’s shields.io, but every other provider also has a custom URL...

**Comment by wooorm** [comment]
P.S. Part of the problem you see is an error in mdast, which didn't support reference images inside reference links. A fix is almost ready!

**Comment by wooorm** [comment]
Boom! Looks so much better indeed!

**Comment by yoshuawuyts** [comment]
:tada: :fireworks: :raised_hands:
