### ISSUE TITLE
Use npm as lookup when local manpage cannot be found

### ISSUE THREAD

**Issue by jbnicolai** [man-n/man-n#22]
How about looking up a manpage on npm when it cannot be found locally? Meaning, doing an implicit `n` if the normal call fails.

Logic would be similar to:

``` bash
man-n --link somePackage || man-n --link n somePackage
```

**Comment by yoshuawuyts** [comment]
+1, I think defaulting to local is a good choice. Probably want to integrate this into `man-n` itself.

**Comment by jbnicolai** [comment]
@yoshuawuyts yeah, I was proposing integrating the 'wrapper' I just wrote in `man-n` itself. Let me whip up a quick PR.

**Comment by yoshuawuyts** [comment]
:D neat!
