### ISSUE TITLE
Add me as maintainer

### ISSUE THREAD

**Issue by jbnicolai** [man-n/man-n#26]
Hi guys,

As you can probably tell by my recent involvement, I'm a big fan of this little project.

Would you be interested in adding me as maintainer, so I can display the project on my profile page and help promote/maintain it?  

No worries if you're not interested ;-)

**Comment by yoshuawuyts** [comment]
+1, I approve :grin:

**Comment by wooorm** [comment]
Me too :) I’ll make it so!

**Comment by jbnicolai** [comment]
:tada: :confetti_ball:
