### ISSUE TITLE
replace logo with screenshot in readme?

### ISSUE THREAD

**Issue by yoshuawuyts** [man-n/man-n#4]
I think showing a screenshot in the header could be more powerful than having a logo. I love having the source for the logo available though (and the logo itself), so maybe move that out to another repo?

**Comment by wooorm** [comment]
Yeah I agree. What project to highlight though? Go for recursion and use `man-n`?

**Comment by yoshuawuyts** [comment]
Haha, that'd be fun :grin:. Though I think `browserify` might be a better candidate since it's one of those projects you repeatedly check out to read the docs.

**Comment by wooorm** [comment]
Yeah and I guess people would be more stoked if they see something they use often.

**Comment by yoshuawuyts** [comment]
Cool, I'll extend https://github.com/man-n/man-n/pull/3 to include a screenshot ++ create a separate repo for the logo source.

**Comment by wooorm** [comment]
Awesome!

**Comment by wooorm** [comment]
You need to use something like rawgit: `https://cdn.rawgit.com/man-n/logo/master/logo.svg`!

**Comment by wooorm** [comment]
Nice ;) haha

**Comment by yoshuawuyts** [comment]
Added a `png` version which solves it :D

**Comment by yoshuawuyts** [comment]
Logo repo now exists as https://github.com/man-n/logo

**Comment by wooorm** [comment]
:+1:
