### ISSUE TITLE
Anchor links

### ISSUE THREAD

**Issue by wooorm** [man-n/man-n#6]
Readme’s often contains quite some anchor links, sometimes to `#readme`, but most of the time to a given heading: e.g., `#see-also`.

Many man-pages use a format like `See FOO`, where, FOO refers to the heading.

An example of this is `man man`, which contains the following:

``` text
OPTIONS
       ...

       -M  path
              Specify  the  list  of directories to search for man pages.  Separate the directories with colons.  An empty list is the same as not specifying -M at all.  See
              SEARCH PATH FOR MANUAL PAGES.

       ...
```

Just inserting `See FOO` won’t fit everywhere, of course, but maybe `link content (see FOO)` would?

Example from franc(n):

``` text
NAME
       ...

       2.  franc is easily forked #supporting-more-or-less-languages to support 335 languages;

       ...
```

Which could be:

``` text
NAME
       ...

       2.  franc is easily forked (see SUPPORTING MORE OR LESS LANGUAGES) to support 335 languages;

       ...
```

**Comment by yoshuawuyts** [comment]
Looks like a reasonable transform; makes a lot of sense. :+1:
