### ISSUE TITLE
Handle document with multiple level 1 headers

### ISSUE THREAD

**Issue by wooorm** [man-n/man-n#7]
Such as, [browserify](https://raw.githubusercontent.com/substack/node-browserify/master/readme.markdown).

roff, the language used for man-pages only supports one title. So mdast-man strips them. Maybe they should be normalised to level-two’s, and the reset of the headers indented an extra level?

**Comment by yoshuawuyts** [comment]
There's also the (probably uncommon) case where there are no `h1` headers. I think the solution you're outlining is the pragmatic / efficient one, so +1 from me.
